export {
  OPENAI_FALLBACK_MODEL,
  OPENAI_PREFERRED_MODEL,
  NVIDIA_API_BASE_URL,
  NVIDIA_DEEPSEEK_MODEL,
  createOpenAIClient,
  createNvidiaClient,
  getOpenAIApiKey,
  getNvidiaApiKey,
  getOpenAIModelPreference,
  getNvidiaModelPreference,
  getAIProviderPreference,
  isAssistantLive,
  getPrimaryProviderLabel,
  resolveProviderOrder,
  isOpenAIModelUnavailableError,
  getAIErrorMessage,
  getOpenAIErrorMessage,
} from "@/lib/ai/assistant-config";
